config/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, reverse_lazy
from django.views.generic import *

from pydnsui.views import *
from pydnsui.decorators import *
from . import forms, models, views

app_name = 'config'
urlpatterns = [
	path('zones',
		login_required(
			ListView.as_view(model = models.Zone)
		),
		name = 'zone-list',
	),
	path('zones/create', 
		login_required(
			CrispyCreateView.as_view(
				model = models.Zone,
				fields = ['name'],
				form_submit_text = 'Submit',
			)
		),
		name = 'zone-create',
	),
	path('zones/deploy',
		login_required(
			views.ZoneDeployView.as_view()
		),
		name = 'zone-deploy',
	),
	path('zones/<int:pk>',
		owner_required(
				views.ZoneDetailView.as_view()
		),
		name = 'zone-detail',
	),
	path('zones/<int:pk>/edit',
		owner_required(
			CrispyUpdateView.as_view(
				model = models.Zone,
				fields = ['name', 'owners'],
				form_submit_text = 'Submit',
			)
		),
		name = 'zone-edit',
	),
	path('zones/<int:pk>/delete', 
		owner_required(
			CrispyDeleteView.as_view(
				model = models.Zone,
				success_url = reverse_lazy('config:zone-list'),
			)
		),
		name = 'zone-delete',
	),
	path('record/<int:zone>/create',
		login_required(
			views.RecordCreateView.as_view()
		),
		name = 'record-create',
	),
	path('record/<int:zone>/edit/<str:serialized>', 
		owner_required(
			views.RecordUpdateView.as_view(),
			model = models.Zone,
			pk_field = 'zone',
		),
		name = 'record-edit',
	),
	path('record/<int:zone>/delete/<str:serialized>', 
		owner_required(
			views.RecordDeleteView.as_view(),
			model = models.Zone,
			pk_field = 'zone',
		),
		name = 'record-delete',
	),
]

dyndns/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path, reverse_lazy
from django.views.generic import *

from pydnsui.views import *
from pydnsui.decorators import *
from . import forms, models, views

app_name = 'ddns'
urlpatterns = [
	path('zones',
		login_required(
			ListView.as_view(model = models.Zone)
		),
		name = 'zone-list',
	),
	path('zone/create',
		login_required(
			CrispyCreateView.as_view(
				model = models.Zone,
				fields = [ 'zone', 'enabled'],
				form_submit_text = 'Submit',
			)
		),
		name = 'zone-create',
	),
	path('zone/<int:pk>',
		owner_required(
			DetailView.as_view(model = models.Zone)
		),
		name = 'zone-detail',
	),
	path('zone/<int:pk>/delete',
		owner_required(
			CrispyDeleteView.as_view(
				model = models.Zone,
				success_url = reverse_lazy('ddns:zone-list'),
			)
		),
		name = 'zone-delete',
	),
	path('zone/<int:pk>/disable',
		owner_required(
			DisableView.as_view(
				model = models.Zone,
				redirect_url = reverse_lazy('ddns:zone-list')
			)
		),
		name = 'zone-disable',
	),
	path('zone/<int:pk>/enable',
		owner_required(
			EnableView.as_view(
				model = models.Zone,
				redirect_url = reverse_lazy('ddns:zone-list')
			)
		),
		name = 'zone-enable',
	),
	path('zone/<int:pk>/create-host',
		owner_required(
			views.HostCreateView.as_view(),
			model = models.Zone,
		),
		name = 'host-create',
	),
	path('host/<int:pk>/delete',
		owner_required(
			views.HostDeleteView.as_view()
		),
		name = 'host-delete',
	),
	path('host/<int:pk>/renew-token',
		owner_required(
			views.HostRenewTokenView.as_view()
		),
		name = 'host-renew-token',
	),
	path('host/<int:pk>/usage',
		owner_required(
			views.HostDetailView.as_view()
		),
		name = 'host-usage',
	),
	path('fritzbox/<int:pk>/<str:token>',
		views.HostUpdateFritzboxView.as_view(),
		name = 'host-update-fritzbox',
	),
]

pydnsui/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path

from pydnsui import views

urlpatterns = [
	path('admin/', admin.site.urls),
	path('accounts/', include('django.contrib.auth.urls')),
	path('config/', include('config.urls')),
	path('',
		login_required(views.IndexView.as_view()),
		name = 'index',
	),
	path('federation/', include('federation.urls', namespace = 'fed')),
	path('dyndns/', include('dyndns.urls')),
]

dyndns/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.crypto import get_random_string

import config

from pydnsui.models import *

class Zone(OwnedModel):
	zone = models.ForeignKey(
		config.models.Zone,
		on_delete = models.CASCADE,
		verbose_name = "Zone configuration",
		related_name = "zone_dyndns",
	)
	enabled = models.BooleanField(
		default = True,
		verbose_name = "DynDNS for this zone is enabled.",
	)

	def __str__(self):
		return self.zone.name
	def get_absolute_url(self):
		return reverse('ddns:zone-detail', kwargs = {
			'pk': self.pk,
		})

class Host(OwnedModel):
	zone = models.ForeignKey(
		Zone,
		on_delete = models.CASCADE,
		verbose_name = "Zone",
		related_name = "hosts",
	)
	name = models.CharField(
		max_length = 255,
		help_text = "Hostname",
	)
	token = models.CharField(
		max_length = 255,
		help_text = "Authorization token for updating this host",
		default = get_random_string(length = 32),
	)
	last_update = models.DateTimeField(
		blank = True,
		null = True,
		editable = False,
		verbose_name = "Last update",
		help_text = "Last successful update."
	)

	def __str__(self):
		return self.zone.zone.name
	def get_absolute_url(self):
		return reverse('ddns:zone-detail', kwargs = {
			'pk': self.zone.pk,
		})
	def generate_new_token(self):
		self.token = get_random_string(length = 32)

dyndns/forms.py
from django import forms

from . import models

class HostCreateForm(forms.ModelForm):
	class Meta:
		model = models.Host
		fields = ['zone', 'name']

	def __init__(self, *args, **kwargs):
		self.zone = kwargs.pop('zone')
		super(HostCreateForm, self).__init__(*args, **kwargs)
		instance = getattr(self, 'instance', None)
		if instance and instance.id:
			self.fields['zone'].widget.attrs['readonly'] = True

	def get_initial_for_field(self, field, field_name):
		if field_name == 'zone':
			return self.zone

dyndns/views.py
from django.conf import settings
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import *

from pydnsui.views import *
from config import dnsutils

from . import forms, models

class HostCreateView(CrispyCreateView):
	model = models.Host
	form_class = forms.HostCreateForm
	template_name = 'dyndns/host_form.html'
	form_submit_text = 'Submit'

	def get_form_kwargs(self):
		kwargs = super(HostCreateView, self).get_form_kwargs()
		kwargs['zone'] = models.Zone.objects.get(pk = self.kwargs['pk'])
		return kwargs

class HostDeleteView(CrispyDeleteView):
	model = models.Host
	
	def get_success_url(self):
		return reverse_lazy('ddns:zone-detail', kwargs = {
			'pk': self.get_object().zone.pk
		})

class HostDetailView(DetailView):
	model = models.Host

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		BASE_URL = 'https://dns.gereon-kremer.de'
		context['endpoints'] = [
			{
				'active': True,
				'id': 'fritzbox',
				'name': 'Fritz!Box',
				'url': BASE_URL + reverse('ddns:host-update-fritzbox', kwargs = {
					'pk': self.get_object().pk,
					'token': self.get_object().token,
				}) + "?ipv4=<ipaddr>&ipv6=<ip6addr>"
			},
		]
		return context
	

class HostRenewTokenView(CrispyUpdateView):
	model = models.Host
	template_name = 'dyndns/host_renew_token_form.html'
	fields = []
	
	def get_success_url(self):
		return reverse_lazy('ddns:zone-detail', kwargs = {
			'pk': self.get_object().zone.pk
		})
	
	def post(self, request, *args, **kwargs):
		obj = self.get_object()
		print(type(obj.token))
		obj.generate_new_token()
		obj.save()
		return super(HostRenewTokenView, self).post(request, *args, **kwargs)

def update_host(pk, token, ipv4 = None, ipv6 = None):
	host = None
	try:
		host = models.Host.objects.get(pk = pk, token = token)
	except:
		return HttpResponseBadRequest('Host not found.')
	
	u = dnsutils.Updater(settings.BIND_SERVER_NAME, host.zone.zone.name)
	u.delete_host(host.name)
	if ipv4:
		u.add({
			'rname': host.name,
			'rttl': 60,
			'rtype': 'A',
			'rdata': ipv4
		})
	if ipv6:
		u.add({
			'rname': host.name,
			'rttl': 60,
			'rtype': 'AAAA',
			'rdata': ipv6
		})
	response = u.send()
	host.last_update = timezone.now()
	host.save_unowned()
	return HttpResponse("Response: {}".format(response))

@method_decorator(csrf_exempt, name='dispatch')
class HostUpdateFritzboxView(View):
	http_method_names = ['get', 'post']

	def get(self, request, *args, **kwargs):
		return update_host(kwargs['pk'], kwargs['token'], request.GET.get('ipv4', None), request.GET.get('ipv6', None))
	def post(self, request, *args, **kwargs):
		return update_host(kwargs['pk'], kwargs['token'], request.POST.get('ipv4', None), request.POST.get('ipv6', None))

dyndns/templates/dyndns/dynhost_confirm_delete.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Delete host {{ object.name }}</h1>

<form method="POST">
	{% csrf_token %}
	Do you really want to remove the DynDNS host <code>{{ object.name }}.{{ object.zone }}</code>? <br />
	{{form.as_p}}
	<div class="form-actions">
		<button type="Submit" class="btn btn-danger">Delete</button>
	</div>
</form>

{% endblock %}

dyndns/templates/dyndns/dynhost_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>New host</h1>

{% crispy form form_helper %}

{% endblock %}

dyndns/templates/dyndns/dynhost_renew_token_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Renew token for {{ object }}</h1>

{% crispy form form_helper %}

{% endblock %}

dyndns/templates/dyndns/dynzone_detail.html
{% extends "base.html" %}

{% load fontawesome_5 %}
{% load helpers %}

{% block content %}
<span class="float-right">
	Owner: {% show_owner object %}
</span>
<h1>DynDNS::Zone {{ object.zone.name }}</h1>

Associated with <a href="{{ object.zone.get_absolute_url }}">{{ object.zone.name }}</a>

{% if error %}
<div class="alert alert-danger">
	{{ error }}
</div>
{% endif %}

<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Token</th>
			<th>Last update</th>
			<th>Owner</th>
			<th>
				<div class="float-right">
					<a class="btn btn-sm btn-primary" href="{% url 'ddns:host-create' object.pk %}">{% fa5_icon 'plus' %} new host</a>
				</div>
			</th>
		</tr>
	</thead>
{% for host in object.hosts.all %}
	{% if host.is_owned %}
	<tr>
		<td><strong>{{ host.name }}</strong>.{{ host.zone }}</td>
		<td><code>{{ host.token }}</code></td>
		<td>{{ host.last_update }}</td>
		<td>{% show_owner host %}</td>
		<td>
			<a class="btn btn-sm btn-primary" href="{% url 'ddns:host-delete' host.pk %}">{% fa5_icon 'trash' %} delete</a>
			<a class="btn btn-sm btn-primary" href="{% url 'ddns:host-renew-token' host.pk %}">{% fa5_icon 'redo' %} renew token</a>
			<a class="btn btn-sm btn-primary" href="{% url 'ddns:host-usage' host.pk %}">{% fa5_icon 'angle-double-up' %} usage</a>
		</td>
	</tr>
	{% endif %}
{% endfor %}
</table>

{% endblock %}

dyndns/templates/dyndns/dynzone_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>New zone</h1>

{% crispy form form_helper %}

{% endblock %}

dyndns/templates/dyndns/dynzone_list.html
{% extends "base.html" %}

{% load fontawesome_5 %}
{% load helpers %}

{% block content %}
<h1>DynDNS::Zones</h1>

<table class="table">
	<thead>
		<tr>
			<th>Zone</th>
			<th>Hosts</th>
			<th>Owner</th>
			<th>
				<span class="float-right">
					<a class="btn btn-sm btn-primary" href="{% url 'ddns:zone-create' %}">{% fa5_icon 'plus' %} New zone</a>
				</span>
			</th>
		</tr>
	</thead>
{% for zone in object_list %}
	<tr{% if not zone.enabled %} class="table-secondary"{% endif %}>
		<th>{% enabled_icon zone %} <a href="{{ zone.get_absolute_url }}">{{ zone.zone.name }}</a></th>
		<td>
			{% for host in zone.hosts.all %}
			<a href="{{ host.get_absolute_url }}"><span class="badge badge-secondary">{{ host.name }}</span></a>
			{% endfor %}
		</td>
		<td>{% show_owner zone %}</td>
		<td>
			{% if zone.enabled %}
				<a class="btn btn-sm btn-secondary" href="{% url 'ddns:zone-disable' zone.pk %}">{% fa5_icon 'ban' %} disable</a>
			{% else %}
				<a class="btn btn-sm btn-primary" href="{% url 'ddns:zone-enable' zone.pk %}">{% fa5_icon 'plus' %} enable</a>
			{% endif %}
			<a class="btn btn-sm btn-primary" href="{% url 'ddns:zone-delete' zone.pk %}">{% fa5_icon 'trash' %} delete</a>
		</td>
	</tr>
{% endfor %}
</table>

{% endblock %}

dyndns/templates/dyndns/host_confirm_delete.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Delete host {{ object.name }}</h1>

<form method="POST">
	{% csrf_token %}
	Do you really want to remove the DynDNS host <code>{{ object.name }}.{{ object.zone }}</code>? <br />
	{{form.as_p}}
	<div class="form-actions">
		<button type="Submit" class="btn btn-danger">Delete</button>
	</div>
</form>

{% endblock %}

dyndns/templates/dyndns/host_detail.html
{% extends "base.html" %}

{% load fontawesome_5 %}

{% block content %}
<h1>DynDNS::Host <code>{{ object.name }}.{{ object.zone }}</code></h1>

Use one of the following endpoints to update this host.

<ul class="nav nav-tabs" id="deployTab" role="tablist">
	{% for endpoint in endpoints %}
		<li class="nav-item">
			<a class="nav-link{% if endpoint.active %} active{% endif %}" id="{{ endpoint.name }}-tab" data-toggle="tab" href="#{{ endpoint.id }}" role="tab" aria-controls="{{ endpoint.id }}" aria-selected="false">{{ endpoint.name }}</a>
		</li>
	{% endfor %}
	</ul>
	<div class="tab-content" id="deployTabContent">
	{% for endpoint in endpoints %}
		<div class="tab-pane fade{% if endpoint.active %} show active{% endif %}" id="{{ endpoint.id }}" role="tabpanel" aria-labelledby="{{ endpoint.id }}-tab">
			<dl>
				<dt>Update URL</dt>
				<dd><code>{{ endpoint.url }}</code></dd>
				<dt>Domain name</dt>
				<dd><code>{{ object.name }}.{{ object.zone }}</code></dd>
				<dt>Username</dt>
				<dd><code>dummy</code></dd>
				<dt>Password</dt>
				<dd><code>dummy</code></dd>
			</dl>
		</div>
	{% endfor %}
</div>

{% endblock %}

dyndns/templates/dyndns/host_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>New host</h1>

{% crispy form form_helper %}

{% endblock %}

dyndns/templates/dyndns/host_renew_token_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Renew token for {{ object }}</h1>

{% crispy form form_helper %}

{% endblock %}

dyndns/templates/dyndns/zone_confirm_delete.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Delete DynDNS::Zone {{ object.zone }}</h1>

<form method="POST">
	{% csrf_token %}
	Do you really want to remove this zone {{ object.name }}? <br />
	All associated hosts will be deleted as well!

	<p>
	{% for host in object.hosts.all %}
	<a href="{{ host.get_absolute_url }}"><span class="badge badge-secondary">{{ host.name }}</span></a>
	{% endfor %}
	</p>

	{{form.as_p}}
	<div class="form-actions">
		<button type="Submit" class="btn btn-danger">Delete</button>
	</div>
</form>

{% endblock %}

dyndns/templates/dyndns/zone_detail.html
{% extends "base.html" %}

{% load fontawesome_5 %}
{% load helpers %}

{% block content %}
<span class="float-right">
	Owner: {% show_owner object %}
</span>
<h1>DynDNS::Zone {{ object.zone.name }}</h1>

Associated with <a href="{{ object.zone.get_absolute_url }}">{{ object.zone.name }}</a>

{% if error %}
<div class="alert alert-danger">
	{{ error }}
</div>
{% endif %}

<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Token</th>
			<th>Last update</th>
			<th>Owner</th>
			<th>
				<div class="float-right">
					<a class="btn btn-sm btn-primary" href="{% url 'ddns:host-create' object.pk %}">{% fa5_icon 'plus' %} new host</a>
				</div>
			</th>
		</tr>
	</thead>
{% for host in object.hosts.all %}
	{% if host.is_owned %}
	<tr>
		<td><strong>{{ host.name }}</strong>.{{ host.zone }}</td>
		<td><code>{{ host.token }}</code></td>
		<td>{{ host.last_update }}</td>
		<td>{% show_owner host %}</td>
		<td>
			<a class="btn btn-sm btn-primary" href="{% url 'ddns:host-delete' host.pk %}">{% fa5_icon 'trash' %} delete</a>
			<a class="btn btn-sm btn-primary" href="{% url 'ddns:host-renew-token' host.pk %}">{% fa5_icon 'redo' %} renew token</a>
			<a class="btn btn-sm btn-primary" href="{% url 'ddns:host-usage' host.pk %}">{% fa5_icon 'angle-double-up' %} usage</a>
		</td>
	</tr>
	{% endif %}
{% endfor %}
</table>

{% endblock %}

dyndns/templates/dyndns/zone_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>New zone</h1>

{% crispy form form_helper %}

{% endblock %}

dyndns/templates/dyndns/zone_list.html
{% extends "base.html" %}

{% load fontawesome_5 %}
{% load helpers %}

{% block content %}
<h1>DynDNS::Zones</h1>

<table class="table">
	<thead>
		<tr>
			<th>Zone</th>
			<th>Hosts</th>
			<th>Owner</th>
			<th>
				<span class="float-right">
					<a class="btn btn-sm btn-primary" href="{% url 'ddns:zone-create' %}">{% fa5_icon 'plus' %} New zone</a>
				</span>
			</th>
		</tr>
	</thead>
{% for zone in object_list %}
	<tr{% if not zone.enabled %} class="table-secondary"{% endif %}>
		<th>{% enabled_icon zone %} <a href="{{ zone.get_absolute_url }}">{{ zone.zone.name }}</a></th>
		<td>
			{% for host in zone.hosts.all %}
			<a href="{{ host.get_absolute_url }}"><span class="badge badge-secondary">{{ host.name }}</span></a>
			{% endfor %}
		</td>
		<td>{% show_owner zone %}</td>
		<td>
			{% if zone.enabled %}
				<a class="btn btn-sm btn-secondary" href="{% url 'ddns:zone-disable' zone.pk %}">{% fa5_icon 'ban' %} disable</a>
			{% else %}
				<a class="btn btn-sm btn-primary" href="{% url 'ddns:zone-enable' zone.pk %}">{% fa5_icon 'plus' %} enable</a>
			{% endif %}
			<a class="btn btn-sm btn-primary" href="{% url 'ddns:zone-delete' zone.pk %}">{% fa5_icon 'trash' %} delete</a>
		</td>
	</tr>
{% endfor %}
</table>

{% endblock %}