config/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, reverse_lazy
from django.views.generic import *

from pydnsui.views import *
from pydnsui.decorators import *
from . import forms, models, views

app_name = 'config'
urlpatterns = [
	path('zones',
		login_required(
			ListView.as_view(model = models.Zone)
		),
		name = 'zone-list',
	),
	path('zones/create', 
		login_required(
			CrispyCreateView.as_view(
				model = models.Zone,
				fields = ['name'],
				form_submit_text = 'Submit',
			)
		),
		name = 'zone-create',
	),
	path('zones/deploy',
		login_required(
			views.ZoneDeployView.as_view()
		),
		name = 'zone-deploy',
	),
	path('zones/<int:pk>',
		owner_required(
				views.ZoneDetailView.as_view()
		),
		name = 'zone-detail',
	),
	path('zones/<int:pk>/edit',
		owner_required(
			CrispyUpdateView.as_view(
				model = models.Zone,
				fields = ['name', 'owners'],
				form_submit_text = 'Submit',
			)
		),
		name = 'zone-edit',
	),
	path('zones/<int:pk>/delete', 
		owner_required(
			CrispyDeleteView.as_view(
				model = models.Zone,
				success_url = reverse_lazy('config:zone-list'),
			)
		),
		name = 'zone-delete',
	),
	path('record/<int:zone>/create',
		login_required(
			views.RecordCreateView.as_view()
		),
		name = 'record-create',
	),
	path('record/<int:zone>/edit/<str:serialized>', 
		owner_required(
			views.RecordUpdateView.as_view(),
			model = models.Zone,
			pk_field = 'zone',
		),
		name = 'record-edit',
	),
	path('record/<int:zone>/delete/<str:serialized>', 
		owner_required(
			views.RecordDeleteView.as_view(),
			model = models.Zone,
			pk_field = 'zone',
		),
		name = 'record-delete',
	),
]

pydnsui/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path

from pydnsui import views

urlpatterns = [
	path('admin/', admin.site.urls),
	path('accounts/', include('django.contrib.auth.urls')),
	path('config/', include('config.urls')),
	path('',
		login_required(views.IndexView.as_view()),
		name = 'index',
	),
	path('federation/', include('federation.urls', namespace = 'fed')),
	path('dyndns/', include('dyndns.urls')),
]

config/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from pydnsui.models import *

class Zone(OwnedModel):
	name = models.CharField(
		max_length = 255,
		unique = True,
	)

	def __str__(self):
		return self.name
	def get_absolute_url(self):
		return reverse('config:zone-detail', kwargs = {
			'pk': self.pk,
		})

config/forms.py
from django import forms

from . import models

class RecordForm(forms.Form):
	rname = forms.CharField(
		max_length = 255,
		label = 'Record name',
	)
	rttl = forms.IntegerField(
		initial = 24*3600,
		label = 'TTL',
	)
	rclass = forms.ChoiceField(
		choices = [("IN", "IN"), ("CH", "CH"), ("HS", "HS"), ("CS", "CS")],
		initial = 'IN',
		label = 'Class',
	)
	rtype = forms.CharField(
		max_length = 16,
		initial = 'A',
		label = 'Type',
	)
	rdata = forms.CharField(
		widget = forms.Textarea,
		label = 'Data',
	)

config/views.py
from django import forms
from django.conf import settings
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.template.response import TemplateResponse
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import *
from django.views.generic import base, detail, edit

from pydnsui.views import *
import federation

import dns
import subprocess

from config.forms import *
from config import dnsutils

class ZoneDetailView(DetailView):
	model = models.Zone

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		try:
			context['records'] = dnsutils.get_zone_records(settings.BIND_SERVER_NAME, self.get_object().name)
		except Exception as e:
			context['error'] = e
		return context

class RecordCreateView(FormHelperMixin, base.TemplateResponseMixin, edit.FormMixin, edit.ProcessFormView):
	form_class = RecordForm
	form_submit_text = 'Submit'
	template_name = 'config/record_form.html'
	
	def get_success_url(self):
		return reverse_lazy('config:zone-detail', kwargs = {'pk': self.kwargs['zone']})

	def form_valid(self, form):
		if form.is_valid():
			zone = models.Zone.objects.get(pk = self.kwargs['zone'])
			u = dnsutils.Updater(settings.BIND_SERVER_NAME, zone.name)
			u.add(form.cleaned_data)
			u.send()
		return super(RecordCreateView, self).form_valid(form)

class RecordUpdateView(FormHelperMixin, base.TemplateResponseMixin, edit.FormMixin, edit.ProcessFormView):
	form_class = RecordForm
	form_submit_text = 'Submit'
	template_name = 'config/record_form.html'
	
	def get_success_url(self):
		print("Was called!")
		return reverse_lazy('config:zone-detail', kwargs = {'pk': self.kwargs['zone']})
	
	def get_initial(self):
		initial = super(RecordUpdateView, self).get_initial()
		initial.update(dnsutils.unserialize(self.kwargs['serialized']))
		return initial
	
	def post(self, request, *args, **kwargs):
		form = self.get_form()
		if form.is_valid():
			zone = models.Zone.objects.get(pk = self.kwargs['zone'])
			u = dnsutils.Updater(settings.BIND_SERVER_NAME, zone.name)
			u.delete(dnsutils.unserialize(self.kwargs['serialized']))
			u.add(form.cleaned_data)
			response = u.send()
			if response.rcode() == dns.rcode.NOERROR:
				return self.form_valid(form)
		return self.render_to_response(self.get_context_data(form = form, error = response))

class RecordDeleteView(base.TemplateResponseMixin, edit.FormMixin, edit.ProcessFormView):
	form_class = forms.Form
	template_name = 'config/record_confirm_delete.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['record'] = dnsutils.unserialize(self.kwargs['serialized'])
		return context

	def post(self, request, *args, **kwargs):
		zone = models.Zone.objects.get(pk = self.kwargs['zone'])
		u = dnsutils.Updater(settings.BIND_SERVER_NAME, zone.name)
		u.delete(dnsutils.unserialize(self.kwargs['serialized']))
		u.send()
		return HttpResponseRedirect(reverse('config:zone-detail', kwargs = {'pk': self.kwargs['zone']}))

class ZoneDeployView(FormHelperMixin, base.TemplateResponseMixin, edit.FormMixin, edit.ProcessFormView):
	form_class = forms.Form
	template_name = 'config/deploy_form.html'
	success_url = reverse_lazy('config:zone-list')
	
	def render_configuration(self):
		files = []
		warnings = []
		for zone in models.Zone.objects.all():
			subordinates = []
			fedzone = None
			try:
				fedzone = federation.models.Zone.objects.get(name = zone.name)
				subordinates = fedzone.get_subordinates()
			except:
				warnings.append("The zone {} is configured locally, but not configured in the federation.".format(zone.name))
			
			files.append({
				'name': zone.name,
				'filename': settings.BIND_CONFIG_DIR + '{}.conf'.format(zone.name),
				'content': render_to_string('config/bind_zone.tpl', {
					'basedir': settings.BIND_CONFIG_DIR,
					'zone': zone,
					'subordinates': subordinates,
				}),
				'include': True,
			})
			files.append({
				'name': 'db.{}'.format(zone.name),
				'filename': settings.BIND_CONFIG_DIR + 'db.{}'.format(zone.name),
				'content': render_to_string('config/bind_db.tpl', {
					'zone': fedzone,
				}),
				'include': False,
			})
		
		for zone in federation.models.Zone.get_subordinate_zones():
			files.append({
				'name': zone.name,
				'filename': settings.BIND_CONFIG_DIR + 'subordinate_{}.conf'.format(zone.name),
				'content': render_to_string('config/bind_subordinate_zone.tpl', {
					'basedir': settings.BIND_CONFIG_DIR,
					'zone': zone,
					'subordinates': zone.get_subordinates(),
				}),
				'include': True,
			})
		
		files.insert(0, {
			'name': 'main.conf',
			'active': True,
			'filename': settings.BIND_CONFIG_DIR + 'main.conf',
			'content': render_to_string('config/bind_main.tpl', {
				'zones': map(lambda z: z['filename'], filter(lambda f: f['include'], files)),
			})
		})
		return files, warnings

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['files'], context['warnings'] = self.render_configuration()
		return context
	
	def post(self, request, *args, **kwargs):
		print("Now we configure the server")
		errors = []
		files, _ = self.render_configuration()
		for file in files:
			print("Writing to {}".format(file['filename']))
			try:
				f = open(file['filename'], 'w')
				f.write(file['content'])
				f.close()
			except Exception as e:
				errors.append(e)
		try:
			res = subprocess.run(settings.BIND_RELOAD_CMD, shell = False, capture_output = True)
			if res.returncode != 0:
				errors.append("Runnning {} failed:\n\n{}".format(" ".join(settings.BIND_RELOAD_CMD), res.stderr.decode('utf8')))
		except Exception as e:
			errors.append(e)
		if errors is not []:
			return TemplateResponse(request, 'config/deploy_error.html', {'errors': errors})
		return super(DeployView, self).post(request, *args, **kwargs)

config/templates/config/deploy_error.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Deploy failed</h1>

<p>
	Deploying the configuration failed.
</p>

{% for e in errors %}
<div class="alert alert-danger" role="alert">
	<pre>{{ e }}</pre>
  </div>
{% endfor %}

{% endblock %}

config/templates/config/deploy_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Deploy configuration</h1>

{% for w in warnings %}
<div class="alert alert-warning">
	{{ w }}
</div>
{% endfor %}

<p>
	Please review the files shown below.
	Do you really want to deploy this configuration?
</p>

<ul class="nav nav-tabs" id="deployTab" role="tablist">
{% for file in files %}
	<li class="nav-item">
		<a class="nav-link{% if file.active %} active{% endif %}" id="{{ file.name }}-tab" data-toggle="tab" href="#{{ file.name }}" role="tab" aria-controls="{{ file.name }}" aria-selected="false">{{ file.name }}</a>
	</li>
{% endfor %}
</ul>
<div class="tab-content" id="deployTabContent">
{% for file in files %}
	<div class="tab-pane fade{% if file.active %} show active{% endif %}" id="{{ file.name }}" role="tabpanel" aria-labelledby="{{ file.name }}-tab">
		Deploy to: <code>{{ file.filename }}</code>

		<div class="card">
			<div class="card-body">
				<pre>{{ file.content }}</pre>
			</div>
		</div>
	</div>
{% endfor %}
</div>


{% crispy form form_helper %}

{% endblock %}

config/templates/config/import_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Sync zone</h1>

{% for r in records %}
{{ r.render }}<br />
{% endfor %}

{% crispy form form_helper %}

{% endblock %}

config/templates/config/record_confirm_delete.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Delete Record</h1>

<form method="POST">
	{% csrf_token %}
	Do you really want to remove the following record? 
	<div class="card card-body"><code>{{ record.rname }} {{ record.rttl }} {{ record.rclass }} {{ record.rtype }} {{ record.rdata }}</code></div>
	
	<div class="form-actions">
		<button type="Submit" class="btn btn-danger">Delete</button>
	</div>
</form>

{% endblock %}

config/templates/config/record_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

{% if form.rname.initial %}
<h1>Change {{ form.rname.initial }}</h1>
{% else %}
<h1>New record</h1>
{% endif %}

{% if error %}
<div class="alert alert-danger"><pre>{{ error }}</pre></div>
{% endif %}

{% crispy form form_helper %}

{% endblock %}

config/templates/config/zone_confirm_delete.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Delete zone {{ object.name }}</h1>

<form method="POST">
	{% csrf_token %}
	Do you really want to remove {{ object.name }}? <br />
	<p class="text-danger">Please note that this will silently remove all records associated with this zone!</p>
	{{form.as_p}}
	<div class="form-actions">
		<button type="Submit" class="btn btn-danger">Delete</button>
	</div>
</form>

{% endblock %}

config/templates/config/zone_deploy_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Sync zone</h1>

{% for c in commands %}
{{ c }}
{% endfor %}
{% if error %}
<div class="alert alert-danger">
	<pre>{{ error }}</pre>
</div>
<a class="btn btn-primary" href="{% url 'config:zone-list' %}">back to zones</a>
{% else %}
{% for r in records %}
{{ r.render }}<br />
{% endfor %}

{% crispy form form_helper %}
{% endif %}

{% endblock %}

config/templates/config/zone_detail.html
{% extends "base.html" %}

{% load fontawesome_5 %}
{% load helpers %}

{% block content %}
<span class="float-right">
	Owner: {% show_owner object %}
</span>
<h1>Zone {{ object.name }}</h1>

{% if error %}
<div class="alert alert-danger">
	{{ error }}
</div>
{% endif %}

<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>TTL</th>
			<th>Class</th>
			<th>Type</th>
			<th>Data</th>
			<th>
				<div class="float-right">
					<a class="btn btn-sm btn-primary" href="{% url 'config:record-create' zone.pk %}">{% fa5_icon 'plus' %} new record</a>
				</div>
			</th>
		</tr>
	</thead>
{% for record in records %}
	<tr>
		<th>{{ record.rname }}</th>
		<td>{{ record.rttl }}</td>
		<td>{{ record.rclass }}</td>
		<td>{{ record.rtype }}</td>
		<td>{{ record.rdata }}</td>
		<td>
			<a class="btn btn-sm btn-primary" href="{% url 'config:record-delete' zone.pk record.serialized %}">{% fa5_icon 'trash' %} delete</a>
			<a class="btn btn-sm btn-primary" href="{% url 'config:record-edit' zone.pk record.serialized %}">{% fa5_icon 'edit' %} edit</a>
		</td>
	</tr>
{% endfor %}
</table>

{% endblock %}

config/templates/config/zone_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
{% if form.name.initial %}
<h1>Change {{ form.name.initial }}</h1>
{% else %}
<h1>New zone</h1>
{% endif %}

{% crispy form form_helper %}

{% endblock %}

config/templates/config/zone_list.html
{% extends "base.html" %}

{% load fontawesome_5 %}
{% load helpers %}

{% block content %}
<h1>Zones</h1>

<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Owner</th>
			<th>
				<span class="float-right">
					<a class="btn btn-sm btn-primary" href="{% url 'config:zone-create' %}">{% fa5_icon 'plus' %} New zone</a>
					<a class="btn btn-sm btn-primary" href="{% url 'config:zone-deploy' %}">{% fa5_icon 'cloud-upload-alt' %} Deploy zones</a>
				</span>
			</th>
		</tr>
	</thead>
{% for zone in object_list %}
	{% if zone.is_owned %}
	<tr>
		<th><a href="{{ zone.get_absolute_url }}">{{ zone.name }}</a></th>
		<td>{% show_owner zone %}</td>
		<td>
			<a class="btn btn-sm btn-primary" href="{% url 'config:zone-edit' zone.pk %}">{% fa5_icon 'edit' %} edit</a>
			<a class="btn btn-sm btn-primary" href="{% url 'config:zone-delete' zone.pk %}">{% fa5_icon 'trash' %} delete</a>
		</td>
	</tr>
	{% endif %}
{% endfor %}
</table>

{% endblock %}