config/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, reverse_lazy
from django.views.generic import *

from pydnsui.views import *
from pydnsui.decorators import *
from . import forms, models, views

app_name = 'config'
urlpatterns = [
	path('zones',
		login_required(
			ListView.as_view(model = models.Zone)
		),
		name = 'zone-list',
	),
	path('zones/create', 
		login_required(
			CrispyCreateView.as_view(
				model = models.Zone,
				fields = ['name'],
				form_submit_text = 'Submit',
			)
		),
		name = 'zone-create',
	),
	path('zones/deploy',
		login_required(
			views.ZoneDeployView.as_view()
		),
		name = 'zone-deploy',
	),
	path('zones/<int:pk>',
		owner_required(
				views.ZoneDetailView.as_view()
		),
		name = 'zone-detail',
	),
	path('zones/<int:pk>/edit',
		owner_required(
			CrispyUpdateView.as_view(
				model = models.Zone,
				fields = ['name', 'owners'],
				form_submit_text = 'Submit',
			)
		),
		name = 'zone-edit',
	),
	path('zones/<int:pk>/delete', 
		owner_required(
			CrispyDeleteView.as_view(
				model = models.Zone,
				success_url = reverse_lazy('config:zone-list'),
			)
		),
		name = 'zone-delete',
	),
	path('record/<int:zone>/create',
		login_required(
			views.RecordCreateView.as_view()
		),
		name = 'record-create',
	),
	path('record/<int:zone>/edit/<str:serialized>', 
		owner_required(
			views.RecordUpdateView.as_view(),
			model = models.Zone,
			pk_field = 'zone',
		),
		name = 'record-edit',
	),
	path('record/<int:zone>/delete/<str:serialized>', 
		owner_required(
			views.RecordDeleteView.as_view(),
			model = models.Zone,
			pk_field = 'zone',
		),
		name = 'record-delete',
	),
]

federation/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path, reverse_lazy
from django.views.generic import *

from pydnsui.views import *
from pydnsui.decorators import *
from . import models, views

app_name = 'fed'
urlpatterns = [
	path('remotes',
		login_required(
			ListView.as_view(model = models.Remote)
		),
		name = 'remote-list',
	),
	path('remotes/create',
		login_required(
			CrispyCreateView.as_view(
				model = models.Remote,
				fields = [ 'name', 'enabled', 'auth_token', 'pull_url', 'pull_token'],
				form_submit_text = 'Submit',
			)
		),
		name = 'remote-create',
	),
	path('remotes/<int:pk>',
		owner_required(
			DetailView.as_view(model = models.Remote)
		),
		name = 'remote-detail',
	),
	path('remotes/<int:pk>/edit',
		owner_required(
			CrispyUpdateView.as_view(
				model = models.Remote,
				fields = [ 'name', 'enabled', 'owners', 'auth_token', 'pull_url', 'pull_token'],
				form_submit_text = 'Submit',
			)
		),
		name = 'remote-edit',
	),
	path('remotes/<int:pk>/delete',
		owner_required(
			CrispyDeleteView.as_view(
				model = models.Remote,
				success_url = reverse_lazy('fed:remote-list'),
			)
		),
		name = 'remote-delete',
	),
	path('remotes/<int:pk>/disable',
		owner_required(
			DisableView.as_view(
				model = models.Remote,
				redirect_url = reverse_lazy('fed:remote-list')
			)
		),
		name = 'remote-disable',
	),
	path('remotes/<int:pk>/enable',
		owner_required(
			EnableView.as_view(
				model = models.Remote,
				redirect_url = reverse_lazy('fed:remote-list')
			)
		),
		name = 'remote-enable',
	),
	path('remotes/<int:pk>/pull',
		owner_required(
			views.PullManualView.as_view()
		),
		name = 'remote-pull',
	),
	path('server',
		login_required(
			ListView.as_view(model = models.Server)
		),
		name = 'server-list',
	),
	path('server/create', 
		login_required(
			CrispyCreateView.as_view(
				model = models.Server,
				fields = [ 'name', 'enabled', 'ipv4', 'ipv6', 'nameserver'],
				form_submit_text = 'Submit',
			)
		),
		name = 'server-create',
	),
	path('server/<int:pk>',
		owner_required(
			DetailView.as_view(model = models.Server)
		),
		name = 'server-detail',
	),
	path('server/<int:pk>/edit',
		owner_required(
			CrispyUpdateView.as_view(
				model = models.Server,
				fields = [ 'name', 'enabled', 'owners', 'ipv4', 'ipv6', 'nameserver'],
				form_submit_text = 'Submit',
			)
		),
		name = 'server-edit',
	),
	path('server/<int:pk>/delete',
		owner_required(
			CrispyDeleteView.as_view(
				model = models.Server,
				success_url = reverse_lazy('fed:server-list'),
			)
		),
		name = 'server-delete',
	),
	path('server/<int:pk>/disable',
		owner_required(
			DisableView.as_view(
				model = models.Server,
				redirect_url = reverse_lazy('fed:server-list')
			)
		),
		name = 'server-disable',
	),
	path('server/<int:pk>/enable',
		owner_required(
			EnableView.as_view(
				model = models.Server,
				redirect_url = reverse_lazy('fed:server-list')
			)
		),
		name = 'server-enable',
	),
	path('server/<int:pk>/disable-pull',
		owner_required(
			DisableView.as_view(
				model = models.Server,
				redirect_url = reverse_lazy('fed:server-list'),
				property_name = 'pull_enabled'
			)
		),
		name = 'server-disable-pull',
	),
	path('server/<int:pk>/enable-pull',
		owner_required(
			EnableView.as_view(
				model = models.Server,
				redirect_url = reverse_lazy('fed:server-list'),
				property_name = 'pull_enabled'
			)
		),
		name = 'server-enable-pull',
	),
	path('server/<int:pk>/pull',
		owner_required(
			views.PullManualView.as_view()
		),
		name = 'server-pull',
	),
	path('zone',
		login_required(
			ListView.as_view(model = models.Zone)
		),
		name = 'zone-list',
	),
	path('zone/create', 
		login_required(
			CrispyCreateView.as_view(
				model = models.Zone,
				fields = [
					'name', 'enabled', 'main', 'subordinates_all', 'subordinates'
				],
				form_submit_text = 'Submit',
			)
		),
		name = 'zone-create',
	),
	path('zone/<int:pk>',
		owner_required(
			DetailView.as_view(model = models.Zone)
		),
		name = 'zone-detail',
	),
	path('zone/<int:pk>/edit',
		owner_required(
			CrispyUpdateView.as_view(
				model = models.Zone,
				fields = [
					'name', 'enabled', 'owners', 'main', 'subordinates_all', 'subordinates'
				],
				form_submit_text = 'Submit',
			)
		),
		name = 'zone-edit',
	),
	path('zone/<int:pk>/disable',
		owner_required(
			DisableView.as_view(
				model = models.Zone,
				redirect_url = reverse_lazy('fed:zone-list')
			)
		),
		name = 'zone-disable',
	),
	path('zone/<int:pk>/enable',
		owner_required(
			EnableView.as_view(
				model = models.Zone,
				redirect_url = reverse_lazy('fed:zone-list')
			)
		),
		name = 'zone-enable',
	),
	path('export/zones',
		views.ExportZonesView.as_view(),
		name = 'export-zones',
	),
]

pydnsui/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path

from pydnsui import views

urlpatterns = [
	path('admin/', admin.site.urls),
	path('accounts/', include('django.contrib.auth.urls')),
	path('config/', include('config.urls')),
	path('',
		login_required(views.IndexView.as_view()),
		name = 'index',
	),
	path('federation/', include('federation.urls', namespace = 'fed')),
	path('dyndns/', include('dyndns.urls')),
]

federation/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models import F, Q
from django.urls import reverse
from django.utils import timezone

from pydnsui.models import *

from datetime import datetime, timedelta

class Remote(OwnedModel):
	name = models.CharField(
		max_length = 255,
		unique = True,
		help_text = "Unique identifier for this remote. Maybe the FQDN?",
	)
	enabled = models.BooleanField(
		default = True,
		verbose_name = "Remote is enabled",
	)
	auth_token = models.CharField(
		max_length = 255,
		blank = True,
		unique = True,
		verbose_name = "Authorization token",
		help_text = "The token this remote should use for pulling zone information.",
	)
	pull_url = models.URLField(
		blank = True,
		verbose_name = "Pull URL",
		help_text = "URL to pull zone information from this remote.",
	)
	pull_token = models.CharField(
		blank = True,
		max_length = 255,
		verbose_name = "Pull Token",
		help_text = "The token used for pulling zone information, should correspond to the authorization token on this remote.",
	)
	pull_last = models.DateTimeField(
		blank = True,
		null = True,
		verbose_name = "Last pull",
		help_text = "Last successful pull from this remote."
	)
	def __str__(self):
		return self.name
	def get_absolute_url(self):
		return reverse('fed:remote-detail', kwargs = {
			'pk': self.pk,
		})
	def is_pull_recent(self):
		if self.pull_last is None:
			return False
		return self.pull_last > timezone.now() - timedelta(hours = 1)


class Server(OwnedModel):
	class Meta:
		ordering = [F('remote').asc(nulls_last = False), 'name']
	name = models.CharField(
		max_length = 255,
		unique = True,
		help_text = "Unique identifier for this server. Maybe the FQDN?",
	)
	remote = models.ForeignKey(
		Remote,
		null = True,
		on_delete = models.CASCADE,
		verbose_name = "Responsible remote",
		help_text = "Remote that introduced this server",
	)
	enabled = models.BooleanField(
		default = True,
		verbose_name = "Server is enabled",
	)
	ipv4 = models.GenericIPAddressField(
		protocol = 'IPv4',
		verbose_name = "IPv4 address",
		help_text = "IPv4 address of the nameserver for the bind query settings.",
	)
	ipv6 = models.GenericIPAddressField(
		protocol = 'IPv6',
		verbose_name = "IPv6 address",
		help_text = "IPv6 address of the nameserver for the bind query settings.",
	)
	nameserver = models.CharField(
		max_length = 255,
		verbose_name = "Nameserver",
		help_text = "Proper FQDN of the nameserver for the NS entries.",
	)

	def __str__(self):
		return self.name
	def get_absolute_url(self):
		return reverse('fed:server-detail', kwargs = {
			'pk': self.pk,
		})

class Zone(OwnedModel):
	name = models.CharField(
		max_length = 255,
		unique = True,
	)
	enabled = models.BooleanField(
		default = True,
		verbose_name = "Zone is enabled",
	)
	main = models.ForeignKey(Server,
		on_delete = models.CASCADE,
		verbose_name = "Main server",
		related_name = "zones_main",
	)
	subordinates_all = models.BooleanField(
		default = True,
		verbose_name = "All servers are subordinates",
	)
	subordinates = models.ManyToManyField(Server,
		blank = True,
		verbose_name = "Subordinate servers",
		related_name = "zones_subordinate",
	)

	def __str__(self):
		return self.name
	def get_absolute_url(self):
		return reverse('fed:zone-detail', kwargs = {
			'pk': self.pk,
		})
	
	def get_nameservers(self):
		return [self.main.nameserver] + [
			s.nameserver for s in self.get_subordinates()
		]
	
	def get_subordinates(self):
		if self.subordinates_all:
			return Server.objects.filter(
				Q(enabled = True) & ~Q(pk = self.main.pk)
			)
		return self.subordinates.all()

	@staticmethod
	def get_subordinate_zones():
		servers = Server.objects.filter(remote = None)
		return Zone.objects.filter(
			Q(enabled = True) & (
				Q(subordinates__in = servers) |
				(Q(subordinates_all = True) & ~Q(main__in = servers))
			)
		)

federation/views.py
from django import forms
from django.conf import settings
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import *
from django.views.generic import base, detail, edit

from pydnsui.views import *
from . import models, pulling

from datetime import datetime
import json
import urllib.parse
import urllib.request

@method_decorator(csrf_exempt, name='dispatch')
class ExportZonesView(View):
	http_method_names = ['post']

	def post(self, request, *args, **kwargs):
		"""
		Use server and token for authorization.
		Export all zones that
		- are enabled
		- belong to a server configured locally
		- have one of the given subordinates
		"""
		try:
			print("Looking for remote {} with token {}".format(request.POST['remote'], request.POST['token']))
			remote = models.Remote.objects.get(auth_token = request.POST['token'])
			subordinates = request.POST.getlist('subordinates')
		except Exception as e:
			print(e)
			return HttpResponse('Invalid token', status = 401)
		print("Exporting zones for pulling server {} and subordinates {}".format(remote.name, subordinates))
		zones = models.Zone.objects.filter(
			Q(enabled = True) &
			Q(main__remote = None) & (
				Q(subordinates_all = True) | Q(subordinates__name__in = subordinates)
			)
		)
		res = {
			'zones': [],
			'server': {},
		}
		servers = set()
		for z in zones:
			res['zones'].append({
				"name": z.name,
				"main": z.main.name,
				"subordinates_all": z.subordinates_all,
				"subordinates": list(map(lambda s: s.name, z.subordinates.all())),
			})
			servers.add(z.main)
			for s in z.subordinates.all():
				servers.add(s)
		for s in servers:
			res['server'][s.name] = {
				'ipv4': s.ipv4,
				'ipv6': s.ipv6,
				'nameserver': s.nameserver,
			}
		return JsonResponse(res, safe = False)

class PullManualView(detail.SingleObjectMixin, FormHelperMixin, base.TemplateResponseMixin, edit.FormMixin, edit.ProcessFormView):
	form_class = forms.Form
	model = models.Remote
	object = None
	template_name = 'federation/pull_form.html'
	success_url = reverse_lazy('fed:remote-list')

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		try:
			zones, p = pulling.get_zones(self.get_object())
			context['modified'] = p.modifications()
			context['warnings'] = p.warnings()
			context['server'] = self.get_object()
			context['zones'] = zones
		except urllib.request.HTTPError as e:
			context['error'] = e
		return context
	
	def post(self, request, *args, **kwargs):
		context = super().get_context_data(**kwargs)
		pulling.pull_and_store(self.get_object())
		return super(PullManualView, self).post(request, *args, **kwargs)

federation/templates/federation/fedzone_detail.html
{% extends "base.html" %}

{% load fontawesome_5 %}

{% block content %}
<h1>Zone {{ object.name }}</h1>

<dl>
	<dt>Name</dt>
	<dd>{{ object.name }}</dd>
	<dt>Enabled</dt>
	<dd>{% if object.enabled %}Yes{% else %}No{% endif %}</dd>
	<dt>Master server</dt>
	<dd><a href="{{ object.master.get_absolute_url }}">{{ object.master.name }}</a></dd>
	<dt>Slave server</dt>
	<dd>
		{% if object.slaves_all %}ALL{% endif %}
		{% for s in object.slaves.all %}
			<a href="{{ s.get_absolute_url }}"><span class="badge badge-secondary">{{ s.name }}</span></a>
		{% endfor %}
	</dd>
</dl>

{% endblock %}

federation/templates/federation/fedzone_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>New zone</h1>

{% crispy form form_helper %}

{% endblock %}

federation/templates/federation/fedzone_list.html
{% extends "base.html" %}

{% load fontawesome_5 %}
{% load helpers %}

{% block content %}
<h1>Federation::Zones</h1>

<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Master</th>
			<th>Slaves</th>
			<th>Owner</th>
			<th><a class="btn btn-sm btn-primary float-right" href="{% url 'fed:zone-create' %}">{% fa5_icon 'plus' %} New zone</a></th>
		</tr>
	</thead>
{% for zone in object_list %}
	{% if zone.is_owned %}
	<tr{% if not zone.enabled %} class="table-secondary"{% endif %}>
		<th>{% enabled_icon zone %} <a href="{{ zone.get_absolute_url }}">{% if zone.master.configured_here %}{% fa5_icon 'home' %}{% endif %} {{ zone.name }}</a></th>
		<td><a href="{{ zone.master.get_absolute_url }}">{{ zone.master.name }}</a></td>
		<td>
			{% if zone.slaves_all %}{% fa5_icon 'globe' title='use all' %}{% endif %}
			{% for s in zone.slaves.all %}
			<a href="{{ s.get_absolute_url }}"><span class="badge badge-secondary">{{ s.name }}</span></a>
			{% endfor %}
		</td>
		<td>{% show_owner zone %}</td>
		<td>
			{% if zone.enabled %}
				<a class="btn btn-sm btn-secondary" href="{% url 'fed:zone-disable' zone.pk %}">{% fa5_icon 'ban' %} disable</a>
			{% else %}
				<a class="btn btn-sm btn-primary" href="{% url 'fed:zone-enable' zone.pk %}">{% fa5_icon 'plus' %} enable</a>
			{% endif %}
			<a class="btn btn-sm btn-primary" href="{% url 'fed:zone-edit' zone.pk %}">{% fa5_icon 'edit' %} edit</a>
		</td>
	</tr>
	{% endif %}
{% endfor %}
</table>

{% endblock %}

federation/templates/federation/pull_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load fontawesome_5 %}

{% block content %}

{% if error %}
<h1>Error while pulling from {{ server.name }}</h1>
<div class="alert alert-danger">
	<pre>{{ error }}</pre>
</div>
{% else %}
<h1>Pull from {{ server.name }}</h1>

{% for w in warnings %}
<div class="alert alert-warning">
	<pre>{{ w }}</pre>
</div>
{% endfor %}
<div class="card-columns">
{% for m in missing %}
	<div class="card alert-warning">
		<div class="card-body">
			<h5 class="card-title">Missing server <code>{{ m.name }}</code></h5>
			<p class="card-text">
				The server <code>{{ m.name }}</code> is not yet configured locally.
				If you pull this data, it will be created automatically with the following configuration obtained from <code>{{ server.name }}</code>:
				<br />
				IPv4: <code>{{ m.ipv4 }}</code>,
				IPv6: <code>{{ m.ipv6 }}</code>,
				Nameserver: <code>{{ m.nameserver }}</code>
			</p>
		</div>
	</div>
{% endfor %}
{% for m in modified %}
	<div class="card alert-warning">
		<div class="card-body">
			<h5 class="card-title">Modified server <code>{{ m.0.name }}</code></h5>
			<p class="card-text">
				The server <code>{{ m.0.name }}</code> has been modified on the remote.
				If you pull this data, it will be changed automatically to the following configuration obtained from <code>{{ server.name }}</code>:
				<br />
				IPv4: <code>{{ m.1.ipv4 }}</code> (was <code>{{ m.0.ipv4 }}</code>),
				IPv6: <code>{{ m.1.ipv6 }}</code> (was <code>{{ m.0.ipv6 }}</code>),
				Nameserver: <code>{{ m.1.nameserver }}</code> (was <code>{{ m.0.nameserver }}</code>)
			</p>
		</div>
	</div>
{% endfor %}
</div>

<div class="card-columns">
{% for zone in zones %}
	<div class="card">
		<div class="card-body">
			<h5 class="card-title">{{ zone.name }}</h5>
			<p class="card-text">
				Master:
				{% if zone.master.pk %}
					<a href="{% url 'fed:server-detail' zone.master.pk %}"><span class="badge badge-secondary">{{ zone.master.name }}</span></a>
				{% else %}
					<span class="badge badge-secondary">{{ zone.master.name }}</span>
				{% endif %},
				Slaves: {% if zone.slaves_all %}{% fa5_icon 'globe' title='use all' %}{% endif %}
				{% for s in zone.slaves %}
					{% if s.pk %}
						<a href="{% url 'fed:server-detail' s.pk %}"><span class="badge badge-secondary">{{ s.name }}</span></a>
					{% else %}
						<span class="badge badge-secondary">{{ s.name }}</span>
					{% endif %}
				{% endfor %}
			</p>
		</div>
	</div>
{% endfor %}
</div>

{% crispy form form_helper %}
{% endif %}

{% endblock %}

federation/templates/federation/remote_confirm_delete.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Delete remote {{ object.name }}</h1>

<form method="POST">
	{% csrf_token %}
	Do you really want to remove the remote {{ object.name }}? <br />
	All associated servers and zones will be deleted as well!

	{% for server in object.server_set.all %}
	{{ server }}
	{% endfor %}

	{{form.as_p}}
	<div class="form-actions">
		<button type="Submit" class="btn btn-danger">Delete</button>
	</div>
</form>

{% endblock %}

federation/templates/federation/remote_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
{% if object %}
<h1>Edit remote {{ object.name }}</h1>
{% else %}
<h1>New remote</h1>
{% endif %}

{% crispy form form_helper %}

{% endblock %}

federation/templates/federation/remote_list.html
{% extends "base.html" %}

{% load fontawesome_5 %}
{% load helpers %}

{% block content %}
<h1>Federation::Remotes</h1>

<p>
	The default remote URL is <code>{% url 'fed:export-zones' %}</code>.
</p>

<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>URL</th>
			<th><a class="btn btn-sm btn-primary float-right" href="{% url 'fed:remote-create' %}">{% fa5_icon 'plus' %} New remote</a></th>
		</tr>
	</thead>
{% for remote in object_list %}
	{% if remote.is_owned %}
	<tr{% if not remote.enabled %} class="table-secondary"{% endif %}>
		<th>{% enabled_icon remote %} <a href="{{ remote.get_absolute_url }}">{{ remote.name }}</a></th>
		<td>
			{% if remote.is_pull_recent %}
				{% fa5_icon 'cloud-download-alt' color='green' title=remote.pull_last %}
			{% else %}
				{% fa5_icon 'cloud-download-alt' color='red' %}
			{% endif %}
			<code>{{ remote.pull_url }}</code>
		</td>
		<td>
			{% if remote.enabled %}
				<a class="btn btn-sm btn-secondary" href="{% url 'fed:remote-disable' remote.pk %}">{% fa5_icon 'ban' %} disable</a>
			{% else %}
				<a class="btn btn-sm btn-primary" href="{% url 'fed:remote-enable' remote.pk %}">{% fa5_icon 'check' %} enable</a>
			{% endif %}
			<a class="btn btn-sm btn-primary" href="{% url 'fed:remote-pull' remote.pk %}">{% fa5_icon 'cloud-download-alt' %} pull</a>
			<a class="btn btn-sm btn-primary" href="{% url 'fed:remote-edit' remote.pk %}">{% fa5_icon 'edit' %} edit</a>
			<a class="btn btn-sm btn-primary" href="{% url 'fed:remote-delete' remote.pk %}">{% fa5_icon 'trash' %} delete</a>
		</td>
	</tr>
	{% endif %}
{% endfor %}
</table>

{% endblock %}

federation/templates/federation/server_confirm_delete.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Delete server</h1>

<form method="POST">
	{% csrf_token %}
	Do you really want to remove {{ object.name }}? <br />
	{{form.as_p}}
	<div class="form-actions">
		<button type="Submit" class="btn btn-danger">Delete</button>
	</div>
</form>

{% endblock %}

federation/templates/federation/server_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<h1>New server</h1>

{% crispy form form_helper %}

{% endblock %}

federation/templates/federation/server_list.html
{% extends "base.html" %}

{% load fontawesome_5 %}
{% load server_list %}

{% block content %}
<h1>Federation::Server</h1>

<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>IPv4</th>
			<th>IPv6</th>
			<th>Nameserver</th>
			<th>Owner</th>
			<th><a class="btn btn-sm btn-primary float-right" href="{% url 'fed:server-create' %}">{% fa5_icon 'plus' %} New server</a></th>
		</tr>
	</thead>
{% for server in object_list %}
	{% if server.is_owned %}
	{% server_row server True %}
	{% endif %}
{% endfor %}
	<thead>
		<tr>
			<th colspan="5">
				Remotely configured servers
			</th>
		</tr>
	</thead>
{% for server in object_list %}
	{% if server.is_owned %}
	{% server_row server False %}
	{% endif %}
{% endfor %}
</table>

{% endblock %}

federation/templates/federation/zone_detail.html
{% extends "base.html" %}

{% load fontawesome_5 %}

{% block content %}
<h1>Zone {{ object.name }}</h1>

<dl>
	<dt>Name</dt>
	<dd>{{ object.name }}</dd>
	<dt>Enabled</dt>
	<dd>{% if object.enabled %}Yes{% else %}No{% endif %}</dd>
	<dt>Master server</dt>
	<dd><a href="{{ object.master.get_absolute_url }}">{{ object.master.name }}</a></dd>
	<dt>Slave server</dt>
	<dd>
		{% if object.slaves_all %}ALL{% endif %}
		{% for s in object.slaves.all %}
			<a href="{{ s.get_absolute_url }}"><span class="badge badge-secondary">{{ s.name }}</span></a>
		{% endfor %}
	</dd>
</dl>

{% endblock %}

federation/templates/federation/zone_list.html
{% extends "base.html" %}

{% load fontawesome_5 %}
{% load helpers %}

{% block content %}
<h1>Federation::Zones</h1>

<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Master</th>
			<th>Slaves</th>
			<th>Owner</th>
			<th><a class="btn btn-sm btn-primary float-right" href="{% url 'fed:zone-create' %}">{% fa5_icon 'plus' %} New zone</a></th>
		</tr>
	</thead>
{% for zone in object_list %}
	{% if zone.is_owned %}
	<tr{% if not zone.enabled %} class="table-secondary"{% endif %}>
		<th>{% enabled_icon zone %} <a href="{{ zone.get_absolute_url }}">{% if zone.master.configured_here %}{% fa5_icon 'home' %}{% endif %} {{ zone.name }}</a></th>
		<td><a href="{{ zone.master.get_absolute_url }}">{{ zone.master.name }}</a></td>
		<td>
			{% if zone.slaves_all %}{% fa5_icon 'globe' title='use all' %}{% endif %}
			{% for s in zone.slaves.all %}
			<a href="{{ s.get_absolute_url }}"><span class="badge badge-secondary">{{ s.name }}</span></a>
			{% endfor %}
		</td>
		<td>{% show_owner zone %}</td>
		<td>
			{% if zone.enabled %}
				<a class="btn btn-sm btn-secondary" href="{% url 'fed:zone-disable' zone.pk %}">{% fa5_icon 'ban' %} disable</a>
			{% else %}
				<a class="btn btn-sm btn-primary" href="{% url 'fed:zone-enable' zone.pk %}">{% fa5_icon 'plus' %} enable</a>
			{% endif %}
			<a class="btn btn-sm btn-primary" href="{% url 'fed:zone-edit' zone.pk %}">{% fa5_icon 'edit' %} edit</a>
		</td>
	</tr>
	{% endif %}
{% endfor %}
</table>

{% endblock %}