config/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, reverse_lazy
from django.views.generic import *

from pydnsui.views import *
from pydnsui.decorators import *
from . import forms, models, views

app_name = 'config'
urlpatterns = [
	path('zones',
		login_required(
			ListView.as_view(model = models.Zone)
		),
		name = 'zone-list',
	),
	path('zones/create', 
		login_required(
			CrispyCreateView.as_view(
				model = models.Zone,
				fields = ['name'],
				form_submit_text = 'Submit',
			)
		),
		name = 'zone-create',
	),
	path('zones/deploy',
		login_required(
			views.ZoneDeployView.as_view()
		),
		name = 'zone-deploy',
	),
	path('zones/<int:pk>',
		owner_required(
				views.ZoneDetailView.as_view()
		),
		name = 'zone-detail',
	),
	path('zones/<int:pk>/edit',
		owner_required(
			CrispyUpdateView.as_view(
				model = models.Zone,
				fields = ['name', 'owners'],
				form_submit_text = 'Submit',
			)
		),
		name = 'zone-edit',
	),
	path('zones/<int:pk>/delete', 
		owner_required(
			CrispyDeleteView.as_view(
				model = models.Zone,
				success_url = reverse_lazy('config:zone-list'),
			)
		),
		name = 'zone-delete',
	),
	path('record/<int:zone>/create',
		login_required(
			views.RecordCreateView.as_view()
		),
		name = 'record-create',
	),
	path('record/<int:zone>/edit/<str:serialized>', 
		owner_required(
			views.RecordUpdateView.as_view(),
			model = models.Zone,
			pk_field = 'zone',
		),
		name = 'record-edit',
	),
	path('record/<int:zone>/delete/<str:serialized>', 
		owner_required(
			views.RecordDeleteView.as_view(),
			model = models.Zone,
			pk_field = 'zone',
		),
		name = 'record-delete',
	),
]

dyndns/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path, reverse_lazy
from django.views.generic import *

from pydnsui.views import *
from pydnsui.decorators import *
from . import forms, models, views

app_name = 'ddns'
urlpatterns = [
	path('zones',
		login_required(
			ListView.as_view(model = models.Zone)
		),
		name = 'zone-list',
	),
	path('zone/create',
		login_required(
			CrispyCreateView.as_view(
				model = models.Zone,
				fields = [ 'zone', 'enabled'],
				form_submit_text = 'Submit',
			)
		),
		name = 'zone-create',
	),
	path('zone/<int:pk>',
		owner_required(
			DetailView.as_view(model = models.Zone)
		),
		name = 'zone-detail',
	),
	path('zone/<int:pk>/delete',
		owner_required(
			CrispyDeleteView.as_view(
				model = models.Zone,
				success_url = reverse_lazy('ddns:zone-list'),
			)
		),
		name = 'zone-delete',
	),
	path('zone/<int:pk>/disable',
		owner_required(
			DisableView.as_view(
				model = models.Zone,
				redirect_url = reverse_lazy('ddns:zone-list')
			)
		),
		name = 'zone-disable',
	),
	path('zone/<int:pk>/enable',
		owner_required(
			EnableView.as_view(
				model = models.Zone,
				redirect_url = reverse_lazy('ddns:zone-list')
			)
		),
		name = 'zone-enable',
	),
	path('zone/<int:pk>/create-host',
		owner_required(
			views.HostCreateView.as_view(),
			model = models.Zone,
		),
		name = 'host-create',
	),
	path('host/<int:pk>/delete',
		owner_required(
			views.HostDeleteView.as_view()
		),
		name = 'host-delete',
	),
	path('host/<int:pk>/renew-token',
		owner_required(
			views.HostRenewTokenView.as_view()
		),
		name = 'host-renew-token',
	),
	path('host/<int:pk>/usage',
		owner_required(
			views.HostDetailView.as_view()
		),
		name = 'host-usage',
	),
	path('fritzbox/<int:pk>/<str:token>',
		views.HostUpdateFritzboxView.as_view(),
		name = 'host-update-fritzbox',
	),
]

federation/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path, reverse_lazy
from django.views.generic import *

from pydnsui.views import *
from pydnsui.decorators import *
from . import models, views

app_name = 'fed'
urlpatterns = [
	path('remotes',
		login_required(
			ListView.as_view(model = models.Remote)
		),
		name = 'remote-list',
	),
	path('remotes/create',
		login_required(
			CrispyCreateView.as_view(
				model = models.Remote,
				fields = [ 'name', 'enabled', 'auth_token', 'pull_url', 'pull_token'],
				form_submit_text = 'Submit',
			)
		),
		name = 'remote-create',
	),
	path('remotes/<int:pk>',
		owner_required(
			DetailView.as_view(model = models.Remote)
		),
		name = 'remote-detail',
	),
	path('remotes/<int:pk>/edit',
		owner_required(
			CrispyUpdateView.as_view(
				model = models.Remote,
				fields = [ 'name', 'enabled', 'owners', 'auth_token', 'pull_url', 'pull_token'],
				form_submit_text = 'Submit',
			)
		),
		name = 'remote-edit',
	),
	path('remotes/<int:pk>/delete',
		owner_required(
			CrispyDeleteView.as_view(
				model = models.Remote,
				success_url = reverse_lazy('fed:remote-list'),
			)
		),
		name = 'remote-delete',
	),
	path('remotes/<int:pk>/disable',
		owner_required(
			DisableView.as_view(
				model = models.Remote,
				redirect_url = reverse_lazy('fed:remote-list')
			)
		),
		name = 'remote-disable',
	),
	path('remotes/<int:pk>/enable',
		owner_required(
			EnableView.as_view(
				model = models.Remote,
				redirect_url = reverse_lazy('fed:remote-list')
			)
		),
		name = 'remote-enable',
	),
	path('remotes/<int:pk>/pull',
		owner_required(
			views.PullManualView.as_view()
		),
		name = 'remote-pull',
	),
	path('server',
		login_required(
			ListView.as_view(model = models.Server)
		),
		name = 'server-list',
	),
	path('server/create', 
		login_required(
			CrispyCreateView.as_view(
				model = models.Server,
				fields = [ 'name', 'enabled', 'ipv4', 'ipv6', 'nameserver'],
				form_submit_text = 'Submit',
			)
		),
		name = 'server-create',
	),
	path('server/<int:pk>',
		owner_required(
			DetailView.as_view(model = models.Server)
		),
		name = 'server-detail',
	),
	path('server/<int:pk>/edit',
		owner_required(
			CrispyUpdateView.as_view(
				model = models.Server,
				fields = [ 'name', 'enabled', 'owners', 'ipv4', 'ipv6', 'nameserver'],
				form_submit_text = 'Submit',
			)
		),
		name = 'server-edit',
	),
	path('server/<int:pk>/delete',
		owner_required(
			CrispyDeleteView.as_view(
				model = models.Server,
				success_url = reverse_lazy('fed:server-list'),
			)
		),
		name = 'server-delete',
	),
	path('server/<int:pk>/disable',
		owner_required(
			DisableView.as_view(
				model = models.Server,
				redirect_url = reverse_lazy('fed:server-list')
			)
		),
		name = 'server-disable',
	),
	path('server/<int:pk>/enable',
		owner_required(
			EnableView.as_view(
				model = models.Server,
				redirect_url = reverse_lazy('fed:server-list')
			)
		),
		name = 'server-enable',
	),
	path('server/<int:pk>/disable-pull',
		owner_required(
			DisableView.as_view(
				model = models.Server,
				redirect_url = reverse_lazy('fed:server-list'),
				property_name = 'pull_enabled'
			)
		),
		name = 'server-disable-pull',
	),
	path('server/<int:pk>/enable-pull',
		owner_required(
			EnableView.as_view(
				model = models.Server,
				redirect_url = reverse_lazy('fed:server-list'),
				property_name = 'pull_enabled'
			)
		),
		name = 'server-enable-pull',
	),
	path('server/<int:pk>/pull',
		owner_required(
			views.PullManualView.as_view()
		),
		name = 'server-pull',
	),
	path('zone',
		login_required(
			ListView.as_view(model = models.Zone)
		),
		name = 'zone-list',
	),
	path('zone/create', 
		login_required(
			CrispyCreateView.as_view(
				model = models.Zone,
				fields = [
					'name', 'enabled', 'main', 'subordinates_all', 'subordinates'
				],
				form_submit_text = 'Submit',
			)
		),
		name = 'zone-create',
	),
	path('zone/<int:pk>',
		owner_required(
			DetailView.as_view(model = models.Zone)
		),
		name = 'zone-detail',
	),
	path('zone/<int:pk>/edit',
		owner_required(
			CrispyUpdateView.as_view(
				model = models.Zone,
				fields = [
					'name', 'enabled', 'owners', 'main', 'subordinates_all', 'subordinates'
				],
				form_submit_text = 'Submit',
			)
		),
		name = 'zone-edit',
	),
	path('zone/<int:pk>/disable',
		owner_required(
			DisableView.as_view(
				model = models.Zone,
				redirect_url = reverse_lazy('fed:zone-list')
			)
		),
		name = 'zone-disable',
	),
	path('zone/<int:pk>/enable',
		owner_required(
			EnableView.as_view(
				model = models.Zone,
				redirect_url = reverse_lazy('fed:zone-list')
			)
		),
		name = 'zone-enable',
	),
	path('export/zones',
		views.ExportZonesView.as_view(),
		name = 'export-zones',
	),
]

pydnsui/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path

from pydnsui import views

urlpatterns = [
	path('admin/', admin.site.urls),
	path('accounts/', include('django.contrib.auth.urls')),
	path('config/', include('config.urls')),
	path('',
		login_required(views.IndexView.as_view()),
		name = 'index',
	),
	path('federation/', include('federation.urls', namespace = 'fed')),
	path('dyndns/', include('dyndns.urls')),
]

templates/base.html
{% load fontawesome_5 %}
{% load helpers %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>pyDNS UI</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
		{% fontawesome_5_static %} 
	</head>
	<body>
		<div id="wrap">
			<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" role="navigation">
				<a class="navbar-brand" href="{% url 'index' %}">pyDNS UI</a>
				<div class="collapse navbar-collapse">
					<ul class="navbar-nav">
					{% if user.is_authenticated %}
						<li class="nav-item"><a class="nav-link active" href="{% url 'config:zone-list' %}">{% fa5_icon 'cogs' %} Local configuration</a></li>
						<li></li>
						<li class="nav-item dropdown">
							<a class="nav-link active dropdown-toggle" id="dropdown-federation" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{% fa5_icon 'cloud' %} Federation</a>
							<div class="dropdown-menu" aria-labelledby="dropdown-federation">
								<a class="dropdown-item" href="{% url 'fed:remote-list' %}">Remotes</a>
								<a class="dropdown-item" href="{% url 'fed:server-list' %}">Server</a>
								<a class="dropdown-item" href="{% url 'fed:zone-list' %}">Zones</a>
							</div>
						</li>
						<li></li>
						<li class="nav-item"><a class="nav-link active" href="{% url 'ddns:zone-list' %}">{% fa5_icon 'network-wired' %} DynDNS</a></li>
					{% endif %}
					</ul>
					<ul class="navbar-nav ml-auto">
						<li class="nav-item navbar-text">
						{% if user.is_authenticated %}
							Logged in as {{user.username}} (<a href="/accounts/logout">{% fa5_icon 'sign-out-alt' %} Logout</a>)
						{% endif %}
						</li>
					</ul>
				</div>
			</nav>
			<div class="container-fluid" style="padding-top: 60px;">
				{% block content %}No Content{% endblock %}
			</div>
			<nav class="navbar fixed-bottom navbar-light bg-light">
				<span class="mx-auto">{% git_version %}</span>
			</nav>
		</div>
	</body>
</html>

templates/index.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<h1>Dashboard</h1>

<div class="card-columns">
	<div class="card">
		<div class="card-body">
			<h5 class="card-title"><a href="{% url 'config:zone-list' %}">Local zones</a> <span class="badge badge-secondary badge-pill float-right">{{ zones|length }} zones</span></h5>
			<p class="card-text">
				{% for zone in zones %}
				<a href="{% url 'config:zone-detail' zone.pk %}"><span class="badge badge-secondary">{{ zone.name }}</span></a>
				{% endfor %}
			</p>
		</div>
	</div>
	<div class="card">
		<div class="card-body">
			<h5 class="card-title"><a href="{% url 'fed:remote-list' %}">Federation::Remotes</a> <span class="badge badge-secondary badge-pill float-right">{{ remotes|length }} remotes</span></h5>
			<p class="card-text">
				{% for remote in remotes %}
				<a href="{% url 'fed:remote-detail' remote.pk %}"><span class="badge badge-secondary">{{ remote.name }}</span></a>
				{% endfor %}
			</p>
		</div>
	</div>
	<div class="card">
		<div class="card-body">
			<h5 class="card-title"><a href="{% url 'fed:server-list' %}">Federation::Servers</a> <span class="badge badge-secondary badge-pill float-right">{{ servers|length }} server</span></h5>
			<p class="card-text">
				<dl>
				{% for server in servers %}
					<dt><a href="{% url 'fed:server-detail' server.pk %}">{{ server.name }}</a> <span class="badge badge-secondary badge-pill float-right">{{ server.ipv4 }} / {{ server.ipv6 }}</span></dt>
					<dd>
						Master zones:
						{% for zone in server.zones_master.all %}
						<a href="{% url 'fed:zone-detail' zone.pk %}"><span class="badge badge-secondary">{{ zone.name }}</span></a>
						{% endfor %}
					</dd>
				{% endfor %}
				</dl>
			</p>
		</div>
	</div>
	<div class="card">
		<div class="card-body">
			<h5 class="card-title"><a href="{% url 'ddns:zone-list' %}">DynDNS::Zones</a> <span class="badge badge-secondary badge-pill float-right">{{ ddns_zones|length }} zones</span></h5>
			<p class="card-text">
				<dl>
				{% for zone in ddns_zones %}
					<dt><a href="{% url 'ddns:zone-detail' zone.pk %}">{{ zone.zone.name }}</a> <span class="badge badge-secondary badge-pill float-right">{{ zone.hosts.all|length }} hosts</span></dt>
					<dd>
						{% for host in zone.hosts.all %}
						<a href="{% url 'ddns:zone-detail' zone.pk %}"><span class="badge badge-secondary">{{ host.name }}</span></a>
						{% endfor %}
					</dd>
				{% endfor %}
				</dl>
			</p>
		</div>
	</div>
</div>
{% endblock %}